### ISSUE TITLE
Upgrade to latest Cucumber versions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-school/bdd-with-cucumber#19]
The release cycle of Cucumber-Ruby, Cucumber-JVM and Cucumber-JS has been quite rapid lately, and we've added some functionality lately that we want Cucumber School users to be exposed to from the first lesson, even if the lesson doesn't cover it explicitly.

The functionality we want people to see as soon as they get started is a banner that gets printed at the end of a run, encouraging the Cucumber user to publish reports. More details here:

* https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.5.0.md

I'd like to be able to update the Cucumber versions in Cucumber School myself with a single command. Something like this:

```versions.yml
cucumber-ruby: 5.0.0
cucumber-jvm: 6.5.1
```

And then simply run `bundle exec rake` to make the required changes/commits.

Right now the build is a bit too complicated for me to figure out as I've mentioned in #17.

Is this something you could look into @iachettifederico?

Cheers,
Aslak

**Comment by aslakhellesoy** [comment]
I'm aware that @sebrose is planning to add chapter 6 about publishing, but I still think it's important that students are using the latest version of Cucumber from chapter 1. That way, if they never make it to chapter 6, they will still have been exposed to this publish functionality.

**Comment by mattwynne** [comment]
In the Ruby and JavaScript versions, the videos show people to type `bundle install cucumber` or whatever, so I don't think updating the versions in the source code used by the scripts is all that urgent / important. It's a detail that sits in the background for us when we need to record footage, but the people watching will never see it.

The urgency would be for JVM projects, where IIRC we have to tell them exactly what to add to their POM file, so here the video footage will be version-dependent, I think.

**Comment by sebrose** [comment]
I've talked this over with @aslakhellesoy 

What we agreed:

1. create a standalone Thinkific course on Cucumber Reports 
2. pom.xml should be updated
  - messaging on Cucumber School explaining why video might show different output
3. an automated mechanism for updating Cucumber versions would be useful

We don't have budget for @iachettifederico to do any of this.
